### PR TITLE
resolve #11  - add speed

### LINKED ISSUE #11: An option to increase or decrease the ball speed
An option to be configured by the user via frontend to decrease or increase the speed of the ball which hits the blocks.

Creativity welcomed 🙂

### PR DESCRIPTION
**Pull request by STM3900**

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Please resolve the conflicts by merging the current updated code.

And this one has 99 lives, and it is supposed to have only 3

**Comment by STM3900** [comment]
And that's it! Sorry for the lives I had added for the tests but I forgot to put them back to 3

**Comment by DhanushNehru** [comment]
After the game is ended , the left over blocks are automatically getting disappeared ?

**Comment by STM3900** [comment]
I did not really understand, what is the problem?

**Pull request merged**
