### PR TITLE
Add block lives

### PR DESCRIPTION
**Pull request by dani0105**
from issue #32

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Seems sometimes the blocks have lives and sometimes even the blocks with 5 lives are cleared on first hit

you can check it for yourself https://deploy-preview-35--breakout-game-dhanushnehru.netlify.app/

**Comment by dani0105** [comment]
Yes, I saw it. I think it's a problem with the collision system that counts multiple hits. Before it was not appreciated because the blocks were destroyed at the moment. I don't know if I solve it in this pull request or if there will be a new issue to solve the problem in another pull request.

**Comment by DhanushNehru** [comment]
Still the same @dani0105

**Comment by dani0105** [comment]
try it now

**Comment by DhanushNehru** [comment]
Actually in mobile view the slider is occupying the entire screen @dani0105

**Comment by dani0105** [comment]
sorry i forgot to change the width of the slider. I put full width to test. i will fix that and upload again

**Pull request merged**
